### ISSUE TITLE
Social Media Signup

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/My-First-Agile-Project#7]
In oder to **include signup with social media network** as a **developer**, I can **split this into User story, one for each social media platform**

### Acceptance Criteria

* Acceptance Criteria 1: Facebook
* Acceptance Criteria 2: X
* Acceptance Criteria 3: Instagram

### Tasks
- [ ] Task 1 breakdown task
- [ ] Task 2 create user story for each
- [ ] Task 3 assign work
